name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Core
      run: |
        cd json_variables
        cargo build --verbose

    - name: Build derive
      run: |
        cd json_variables_derive
        cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
